import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import NavbarProduct from '@/components/navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Official Website Kosyuk',
  description: 'Generated by create next app',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const isLogin = true
  return (
    <html lang="en">
      <body>
        <div className='bg-white'>
         <NavbarProduct isLogin={isLogin} />
          {children}
        </div>
      </body>
    </html>
  )
}