import Sidebar from '@/components/sidebar';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'Official Website SERLOK AJA',
    description: 'Generated by create next app',
}

export default function NestedLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
                <div style={{ display: 'flex', height: '100vh' }}>
                    <div style={{ flex: '0 0 250px', position: 'fixed', top: 0, left: 0, bottom: 0, height: '100vh' }}>
                        <Sidebar />
                    </div>
                    <div style={{ flex: 1, marginLeft: '250px', height: '100vh', overflowY: 'auto' }}>
                        {children}
                    </div>
                </div>
        </>
    )
}
