import Sidebar from '@/components/sidebar';
import type { Metadata } from 'next';
import { CookiesProvider } from 'next-client-cookies/server';

export const metadata: Metadata = {
    title: 'Official Website Kosyuk',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            <CookiesProvider>
                <div style={{ display: 'flex', height: '100vh' }}>
                    <div style={{ flex: '0 0 250px', position: 'fixed', top: 0, left: 0, bottom: 0, height: '100vh' }}>
                        <Sidebar />
                    </div>
                    <div style={{ flex: 1, marginLeft: '250px', height: '100vh', overflowY: 'auto' }}>
                        {children}
                    </div>
                </div>
            </CookiesProvider>
        </>
    )
}
