import NavbarProduct from "@/components/navbar";
import type { Metadata } from "next";
import { CookiesProvider } from "next-client-cookies/server";

export const metadata: Metadata = {
  title: "Official Website Kosyuk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const isLogin = false;
  return (
    <>
    <NavbarProduct isLogin={isLogin} />
      <CookiesProvider>
        <div className="bg-white">
          {children}
        </div>
      </CookiesProvider>
    </>
  );
}
